import {call, exportText, shareText, subscribe, type Entry} from './api';
import {tr, locale, errorText} from './i18n';
import {icon, escapeHtml as esc} from './icons';

type Rule={id:string;name:string;instruction:string};
type TextModel={id:string;name:string;contextLength:number;maxCompletionTokens:number|null};
type Result={id:string;ruleId:string;ruleName:string;instruction:string;model:string;createdAt:number;text:string};
type Context={entry:()=>Entry|null;transcript:()=>string;saved:()=>boolean;busy:()=>boolean;render:()=>void;notice:(message:string,error?:boolean)=>void;begin:()=>void;end:()=>void;confirm:(title:string,message:string,action:string,danger?:boolean)=>Promise<boolean>;updated:(entry:Entry)=>void;showResults:()=>void;configure:()=>void;hasToken:()=>boolean;copy:(text:string)=>void};
let context:Context;
let rules:Rule[]=[],rulesLoaded=false,rulesLoading=false,rulesError='',draft:Rule|null=null,draftDirty=false;
let textModels:TextModel[]=[],modelLoading=false,modelError='',modelSearch='',picker=false;
let chosenRule='',chosenModel=localStorage.getItem('hearfolio-text-model')||'',processing=false,partial='',runningRecord='',runId='';
const starterRules=()=>[
  {name:tr('Краткое содержание'),instruction:tr('Составь краткое содержание расшифровки на языке исходного текста. Выдели главные мысли. Не добавляй факты, которых нет в записи.')},
  {name:tr('Решения встречи'),instruction:tr('Извлеки из расшифровки принятые решения, открытые вопросы и следующие шаги. Отдельно укажи ответственных и сроки, если они названы. Не придумывай недостающие сведения.')},
  {name:tr('Список действий'),instruction:tr('Составь список конкретных действий из расшифровки. Для каждого укажи исполнителя и срок, если они есть в тексте. Не добавляй новые задачи.')},
];
export function setupPostprocess(value:Context){context=value;void subscribe<{recordId:string;runId:string;text:string}>('postprocess-text',payload=>{if(!processing||payload.recordId!==runningRecord||(runId&&payload.runId!==runId))return;runId=payload.runId;partial=payload.text;const element=document.querySelector('#processing-text');if(element){const follow=element.scrollHeight-element.scrollTop-element.clientHeight<90;element.textContent=partial;if(follow)element.scrollTop=element.scrollHeight;}}).catch(error=>context.notice(errorText(error),true));}
export function hasRuleDraft(){return draftDirty;}
export async function mayLeaveRules(){if(!draftDirty)return true;if(!await context.confirm(tr('Правило не сохранено'),tr('Сохраните правило перед уходом или продолжите без изменений.'),tr('Продолжить без изменений'),false))return false;draft=null;draftDirty=false;return true;}
export async function loadRules(){if(rulesLoading)return;rulesLoading=true;rulesError='';context.render();try{rules=await call<Rule[]>('list_postprocess_rules');rulesLoaded=true;if(!rules.some(rule=>rule.id===chosenRule))chosenRule=rules[0]?.id||'';}catch(error){rulesError=errorText(error);}finally{rulesLoading=false;context.render();}}
export function ensureRules(){if(!rulesLoaded&&!rulesLoading)void loadRules();}
export function rulesHtml(){return `<div class="page-heading"><div><h1>${tr('Правила обработки')}</h1><p>${tr('Сохраните инструкции, чтобы получать нужный результат из расшифровки.')}</p></div></div><div class="rules-page"><button type="button" class="text-button" data-view="settings">${tr('Настройки')}${icon('chevron')}</button>${draft?`<form id="rule-form" class="rule-editor"><h2>${tr(draft.id?'Изменить правило':'Новое правило')}</h2><label class="field"><span>${tr('Название')}</span><input name="name" maxlength="200" required ${context.busy()?'disabled':''} value="${esc(draft.name)}" placeholder="${tr('Например, итоги встречи')}"></label><label class="field"><span>${tr('Инструкция')}</span><textarea name="instruction" maxlength="8000" required ${context.busy()?'disabled':''} rows="7" placeholder="${tr('Опишите, что нужно сделать с расшифровкой')}">${esc(draft.instruction)}</textarea><small>${tr('Правило применяется к тексту. Модель выбирается перед обработкой.')}</small></label><div class="rule-form-actions"><button class="primary" type="submit" ${context.busy()?'disabled':''}>${tr('Сохранить правило')}</button><button class="secondary" type="button" id="rule-cancel" ${context.busy()?'disabled':''}>${tr('Отмена')}</button></div></form>`:`<div class="rules-toolbar"><h2>${tr('Ваши правила')}</h2><button class="secondary" id="rule-new" ${context.busy()?'disabled':''}>${icon('plus')}${tr('Создать правило')}</button></div>`}${rulesLoading?`<p class="rules-status"><span class="spinner"></span>${tr('Загружаем правила…')}</p>`:rulesError?`<div class="inline-error" role="alert">${esc(rulesError)}<button class="text-button" id="rules-retry">${tr('Повторить')}</button></div>`:rules.length?`<div class="rule-list">${rules.map(rule=>`<article class="rule-card"><div><h2>${esc(rule.name)}</h2><p>${esc(rule.instruction)}</p></div><div class="rule-card-actions"><button class="icon-button" data-rule-edit="${esc(rule.id)}" aria-label="${esc(tr('Изменить правило')+' '+rule.name)}" ${context.busy()?'disabled':''}>${icon('edit')}</button><button class="icon-button" data-rule-delete="${esc(rule.id)}" aria-label="${esc(tr('Удалить правило')+' '+rule.name)}" ${context.busy()?'disabled':''}>${icon('trash')}</button></div></article>`).join('')}</div>`:`<p class="rules-status">${tr('Пока нет правил. Создайте своё или начните с примера.')}</p>`}<section class="rule-starters"><h2>${tr('Начните с примера')}</h2><p>${tr('Пример можно изменить и сохранить как своё правило.')}</p>${starterRules().map((rule,index)=>`<button class="starter-rule" data-rule-starter="${index}" ${context.busy()?'disabled':''}><span>${esc(rule.name)}</span>${icon('plus')}</button>`).join('')}</section></div>`;}
function modelResults(){const matches=textModels.filter(model=>`${model.name} ${model.id}`.toLocaleLowerCase().includes(modelSearch.toLocaleLowerCase()));return modelLoading?`<p class="catalog-empty"><span class="spinner"></span> ${tr('Загружаем модели…')}</p>`:modelError?`<p class="catalog-empty" role="alert">${esc(modelError)}</p>`:!matches.length?`<p class="catalog-empty">${tr(textModels.length?'Модели не найдены':'Нет моделей для обработки текста')}</p>`:matches.map(model=>`<button class="catalog-option ${model.id===chosenModel?'selected':''}" type="button" data-text-model="${esc(model.id)}"><span><strong>${esc(model.name)}</strong><small>${esc(model.id)}</small></span>${model.id===chosenModel?icon('check'):''}</button>`).join('');}
export function postprocessHtml(){if(!context.transcript()||!context.saved())return '';const chosen=textModels.find(model=>model.id===chosenModel);return `<section class="postprocess-controls" tabindex="-1" aria-label="${tr('Обработать текст')}"><div class="section-heading"><h2>${tr('Обработать текст')}</h2><button type="button" class="text-button" data-view="rules" ${context.busy()?'disabled':''}>${tr('Правила')}${icon('chevron')}</button></div><p>${tr('Получите итог, решения или список действий по сохранённому правилу.')}</p>${!rules.length?`<button type="button" class="secondary" data-view="rules" ${context.busy()?'disabled':''}>${tr(rulesLoading?'Загружаем правила…':'Создать правило')}</button>`:`<div class="processing-selectors"><label class="field"><span>${tr('Правило')}</span><select id="processing-rule" ${context.busy()?'disabled':''}>${rules.map(rule=>`<option value="${esc(rule.id)}" ${rule.id===chosenRule?'selected':''}>${esc(rule.name)}</option>`).join('')}</select></label><div class="field text-model-field"><span>${tr('Модель для текста')}</span><button type="button" class="text-model-button" id="text-model-picker" ${context.busy()?'disabled':''}><span>${esc(chosen?.name||chosenModel||tr('Выбрать модель'))}</span>${icon('chevron')}</button></div></div><button type="button" class="primary" id="apply-postprocess" ${context.busy()||!context.hasToken()||!chosenModel||!chosenRule?'disabled':''}>${processing?'<span class="spinner"></span>':icon('file')}${tr(processing?'Обрабатываем текст…':'Применить правило')}</button>`}${!context.hasToken()?`<div class="processing-connection"><span>${tr('Добавьте API token OpenRouter.')}</span><button type="button" class="text-button" id="processing-configure" ${context.busy()?'disabled':''}>${tr('Настроить OpenRouter')}${icon('chevron')}</button></div>`:''}${rulesError?`<div class="inline-error">${esc(rulesError)}<button class="text-button" id="rules-retry">${tr('Повторить')}</button></div>`:''}</section>`;}
export function textPickerHtml(){return !picker?'':`<div class="catalog-backdrop" id="text-picker-backdrop"><section class="model-catalog" role="dialog" aria-modal="true" aria-labelledby="text-picker-title"><div class="catalog-heading"><strong id="text-picker-title">${tr('Модель для обработки текста')}</strong><button class="icon-button" id="text-picker-close" aria-label="${tr('Закрыть')}">${icon('close')}</button></div><label class="search-field">${icon('search')}<input id="text-model-search" type="search" value="${esc(modelSearch)}" placeholder="${tr('Найти модель')}" aria-label="${tr('Найти модель')}"></label><div id="text-model-results">${modelResults()}</div><button class="text-button" id="text-model-refresh">${tr('Обновить каталог')}</button></section></div>`;}
export function textPickerOpen(){return picker;}
export function resultsHtml(){const results=(context.entry() as (Entry&{results?:Result[]})|null)?.results||[];return `<div class="processing-results">${processing?`<section class="processing-live"><div class="section-heading"><h2>${tr('Обрабатываем текст…')}</h2><span class="badge">${tr('Не сохранено')}</span></div><article id="processing-text" class="transcript processing-text">${esc(partial)||tr('Результат появится по мере обработки.')}</article></section>`:''}${results.length?results.slice().sort((a,b)=>b.createdAt-a.createdAt).map(result=>`<section class="processed-result"><div class="processed-heading"><div><h2>${esc(result.ruleName)}</h2><p>${new Date(result.createdAt).toLocaleString(locale(),{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})} · ${esc(result.model)}</p></div><div class="result-actions"><button class="icon-button" data-result-copy="${esc(result.id)}" aria-label="${tr('Копировать результат')}" title="${tr('Копировать результат')}">${icon('copy')}</button><button class="icon-button" data-result-share="${esc(result.id)}" aria-label="${tr('Поделиться результатом')}" title="${tr('Поделиться результатом')}">${icon('share')}</button><button class="icon-button" data-result-export="${esc(result.id)}" aria-label="${tr('Экспортировать текст')}" title="${tr('Экспортировать текст')}">${icon('download')}</button></div></div><article class="transcript processing-text">${esc(result.text)}</article></section>`).join(''):!processing?`<div class="record-empty"><div class="empty-symbol">${icon('file')}</div><h2>${tr('Пока нет результатов')}</h2><p>${tr('Примените правило к расшифровке. Исходный текст сохранится отдельно.')}</p></div>`:''}</div>`;}
async function loadTextModels(){if(modelLoading)return;modelLoading=true;modelError='';context.render();try{textModels=await call<TextModel[]>('list_text_models');if(!textModels.some(model=>model.id===chosenModel))chosenModel='';}catch(error){modelError=errorText(error);}finally{modelLoading=false;context.render();}}
async function apply(){if(processing||context.busy()||!context.hasToken()||!context.entry()||!context.saved()||!chosenRule||!chosenModel)return;const id=context.entry()!.id;processing=true;partial='';runningRecord=id;runId='';context.begin();context.showResults();context.render();try{const result=await call<Result>('apply_postprocess',{id,ruleId:chosenRule,model:chosenModel});const entry=context.entry() as Entry&{results?:Result[]};if(entry?.id===id)context.updated({...entry,results:[...(entry.results||[]).filter(item=>item.id!==result.id),result]} as Entry);localStorage.setItem('hearfolio-text-model',chosenModel);context.notice(tr('Результат сохранён'));}catch(error){context.notice(`${tr('Не удалось обработать текст: ')}${errorText(error)}`,true);}finally{processing=false;partial='';runningRecord='';runId='';context.end();context.render();}}
export function bindPostprocess(){
  document.querySelector('#processing-configure')?.addEventListener('click',context.configure);
  document.querySelector('#rule-new')?.addEventListener('click',async()=>{if(!await mayLeaveRules())return;draft={id:'',name:'',instruction:''};draftDirty=false;context.render();});
  document.querySelector('#rules-retry')?.addEventListener('click',loadRules);
  document.querySelector('#rule-cancel')?.addEventListener('click',async()=>{if(!await mayLeaveRules())return;draft=null;context.render();});
  document.querySelectorAll<HTMLElement>('[data-rule-starter]').forEach(element=>element.onclick=async()=>{if(!await mayLeaveRules())return;draft={id:'',...starterRules()[Number(element.dataset.ruleStarter)]};draftDirty=true;context.render();});
  document.querySelectorAll<HTMLElement>('[data-rule-edit]').forEach(element=>element.onclick=async()=>{if(!await mayLeaveRules())return;draft={...rules.find(rule=>rule.id===element.dataset.ruleEdit)!};draftDirty=false;context.render();});
  document.querySelectorAll<HTMLElement>('[data-rule-delete]').forEach(element=>element.onclick=async()=>{if(!await mayLeaveRules())return;const id=element.dataset.ruleDelete!;if(!await context.confirm(tr('Удалить правило?'),tr('Сохранённые результаты останутся в записях.'),tr('Удалить правило')))return;context.begin();context.render();try{await call('delete_postprocess_rule',{id});rules=rules.filter(rule=>rule.id!==id);if(chosenRule===id)chosenRule=rules[0]?.id||'';draft=null;context.notice(tr('Правило удалено'));}catch(error){context.notice(errorText(error),true);}finally{context.end();context.render();}});
  const form=document.querySelector<HTMLFormElement>('#rule-form');form?.addEventListener('input',()=>{const data=new FormData(form);draft={...draft!,name:String(data.get('name')),instruction:String(data.get('instruction'))};draftDirty=true;});form?.addEventListener('submit',async event=>{event.preventDefault();if(!draft||context.busy()||!form.reportValidity())return;const value={...draft,name:draft.name.trim(),instruction:draft.instruction.trim()};if(!value.name||!value.instruction){context.notice(tr('Заполните название и инструкцию'),true);return;}context.begin();context.render();try{const saved=await call<Rule>('save_postprocess_rule',{rule:value});rules=[...rules.filter(rule=>rule.id!==saved.id),saved];chosenRule=saved.id;draft=null;draftDirty=false;context.notice(tr('Правило сохранено'));}catch(error){context.notice(`${tr('Не удалось сохранить правило: ')}${errorText(error)}`,true);}finally{context.end();context.render();}});
  document.querySelector<HTMLSelectElement>('#processing-rule')?.addEventListener('change',event=>{chosenRule=(event.target as HTMLSelectElement).value;});
  document.querySelector('#text-model-picker')?.addEventListener('click',()=>{picker=true;context.render();if(!textModels.length)void loadTextModels();});
  const close=()=>{picker=false;modelSearch='';context.render();document.querySelector<HTMLButtonElement>('#text-model-picker')?.focus();};document.querySelector('#text-picker-close')?.addEventListener('click',close);const backdrop=document.querySelector('#text-picker-backdrop');backdrop?.addEventListener('click',event=>{if(event.target===backdrop)close();});backdrop?.addEventListener('keydown',event=>{const key=event as KeyboardEvent;if(key.key==='Escape'){key.stopPropagation();close();}if(key.key==='Tab'){const items=Array.from(backdrop.querySelectorAll<HTMLElement>('button:not(:disabled),input'));if(key.shiftKey&&document.activeElement===items[0]){key.preventDefault();items[items.length-1]?.focus();}else if(!key.shiftKey&&document.activeElement===items[items.length-1]){key.preventDefault();items[0]?.focus();}}});document.querySelector('#text-model-refresh')?.addEventListener('click',loadTextModels);
  const bindModels=()=>document.querySelectorAll<HTMLElement>('[data-text-model]').forEach(element=>element.onclick=()=>{chosenModel=element.dataset.textModel!;close();});bindModels();document.querySelector<HTMLInputElement>('#text-model-search')?.addEventListener('input',event=>{modelSearch=(event.target as HTMLInputElement).value;document.querySelector('#text-model-results')!.innerHTML=modelResults();bindModels();});
  document.querySelector('#apply-postprocess')?.addEventListener('click',apply);
  const results=(context.entry() as Entry&{results?:Result[]})?.results||[];for(const action of ['copy','share','export'])document.querySelectorAll<HTMLElement>(`[data-result-${action}]`).forEach(element=>element.onclick=()=>{const result=results.find(item=>item.id===element.dataset[`result${action[0].toUpperCase()+action.slice(1)}`]);if(!result)return;const name=`${context.entry()?.name||tr('Запись')} — ${result.ruleName}`;if(action==='copy')context.copy(result.text);else void (action==='share'?shareText(name,result.text):exportText(name.replace(/[\/\\:\u0000-\u001f]/g,'-')+'.txt',result.text)).catch(error=>context.notice(errorText(error),true));});
}
